export { VitalsInput, type VitalsData } from './VitalsInput'
export { ConsultationForm, type ConsultationFormData } from './ConsultationForm'
export { ConsultationHistory } from './ConsultationHistory'
export { NewConsultationDialog } from './NewConsultationDialog'
export { ConsultationVitalsCard } from './ConsultationVitalsCard'
export { ConsultationActionsBar } from './ConsultationActionsBar'
